<?php
/**
 * Deny changing billing addresses via Magento frontend
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Customer
 * @package    Quafzi_FixedBillingAddress
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Thomas Birke <tbirke@netextreme.de>
 */
?>
<?php
/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Address Book') ?></h1>
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2><?php echo $this->__('Default Addresses') ?></h2>
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
<?php /* THIS IS THE ONLY CHANGE OF THIS FILE */ ?>
                <?php if (false === Mage::helper('quafzi_fixedbillingaddress/data')->isAddressFixed()): ?>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
                <?php endif; ?>
<?php /* END OF CHANGE */ ?>
           </li>
        <?php else: ?>
            <li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            </li>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="item">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
            </li>
        <?php else: ?>
            <li class="item empty">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
    <div class="col-2 addresses-additional">
        <h2><?php echo $this->__('Additional Address Entries') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?>
                </address>
                <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
